# Generated by Django 5.0.1 on 2024-01-25 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saloons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='saloon',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saloons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saloon',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='saloons', to='saloons.service'),
        ),
    ]
