# Generated by Django 4.2.9 on 2024-01-28 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saloons', '0002_alter_sign_options_remove_sign_end_remove_sign_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_signs', to='saloons.master'),
        ),
    ]
