# Generated by Django 5.0.1 on 2024-01-25 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloons', '0004_master'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='master',
            options={'ordering': ('name',), 'verbose_name': 'Мастер', 'verbose_name_plural': 'Мастера'},
        ),
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_signs', to='saloons.saloon')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_signs', to='saloons.master')),
                ('saloon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saloon_signs', to='saloons.saloon')),
            ],
        ),
    ]
