# Generated by Django 4.2.9 on 2024-01-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloons', '0007_administrator_client_remove_saloon_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='orders',
            field=models.IntegerField(default=0),
        ),
    ]
