# Generated by Django 5.0.1 on 2024-01-26 20:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloons', '0009_service_duration_service_price_alter_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='master',
            name='saloons',
            field=models.ManyToManyField(blank=True, related_name='saloon_masters', to='saloons.saloon'),
        ),
    ]
